Constructor verification for heap allocation and nested structs/classes.
verifast/verifast pull request #257
Opened 2021-12-16 09:08 UTC by NielsMommen

- Constructors are verified and their contract is checked when a new object is allocated on the heap.
- Constructors are checked for nested struct/class allocation. I.e., when a field in a struct/class is a struct/class.
- Currently, a default constructor has to be specified explicitly for a struct/class.
- Destructors are not supported.
- The `delete` expression is only supported when a struct/class does not have nested structs/classes.
- Allocation of structs/classes on the stack is not supported.

2022-01-05 07:27 UTC, btj requested changes
Good job, Niels! I have just a few minor comments.

2022-01-05 07:27 UTC, btj commented on src/verify_expr.ml
> +    sn, (sloc, body, spad_sym, ssize)
Fix indentation

2022-01-05 07:27 UTC, btj commented on src/verify_expr.ml
> +  (* CXX: check defualt initializers *)
typo

2022-01-05 07:27 UTC, btj commented on src/cxx_frontend/ast_exporter/DeclSerializer.cpp
> +  // Implicit functions have a definiton, but only have a body when
Typo

2022-01-05 08:25 UTC, NielsMommen commented on src/ast.ml
> +      ((string * (expr * bool (* is written *)) option) list (* init list *) * (stmt list * loc (* close brace *))) option *
- Make two separate optional components or insert a newline for readability?
- The init list contains every field that will be initialised by the constructor invocation. If a record field has no explicit initialiser, Clang will generate one. In that case, `'field_name', Some ('ctor mangled name', false)` is present in the init list. For a primitive field that has no explicit initialiser, `'field_name', None` is present. E.g.:
  ```c++
  struct Foo {
    int _f;
  
    Foo() : _f(0) {}
    Foo(int f) : _f(f) {}
  };
  
  struct Bar {
    int _i;
    int _j = 0;
    Foo _f1;
    Foo _f2;
  
    Bar() : f2(2) {}
  };
  ```
  has following init lists
  - `Foo()`: `_f, Some ('0', true)`
  - `Foo(int f)`: `_f, Some('f', true)`
  - `Bar()`: `_i, None`; `_j, Some('0', true)`; `_f1, Some('Foo()', false)`; `_f2, Some ('Foo(2)', true)`
  Hence, the difference between `None` and `Some (..., false)` is that the former refers to a default initialisation of a primitive and the latter refers to an implicit default initialisation of a record. We need the expression generated by Clang in the latter case to know the default constructor's mangled name that should be checked.

2022-01-05 09:39 UTC, btj commented on src/ast.ml
> +      ((string * (expr * bool (* is written *)) option) list (* init list *) * (stmt list * loc (* close brace *))) option *
- Separate components: never mind, I had not noticed it was all one `option`.
- Init list: thanks, that clears it up!

2022-01-06 07:50 UTC, NielsMommen commented on src/verifast1.ml
> +      e, t, None
Added these well formed expressions that take a `type_`.

2022-01-06 07:52 UTC, NielsMommen commented on src/ast.ml
> +      string * (* name *)
Removed the name.

2022-01-06 07:52 UTC, NielsMommen commented on src/ast.ml
> +      (type_expr * string) list * (* params *)
Removed the parameter list.

2022-01-06 07:55 UTC, merged