[Rust] rc_u32 (Draft)
verifast/verifast pull request #523
Opened 2024-06-04 15:56 UTC by Nima-Rahimi-Foroushaani

It has not been cleaned up, so some debug prints and notes are in the files. I added my concerns about the proof to `rc_u32.rs` as `TODO` notes.

2024-06-04 22:57 UTC, btj requested changes
Excellent! If you just apply the few requested changes and do a bit of cleanup, we can merge this!

2024-06-04 22:57 UTC, btj commented on bin/rust/std/lib.rsspec
> +    }
Since Box is not being used, leave it out of this PR.

2024-06-04 22:57 UTC, btj commented on tests/rust/safe_abstraction/rc_u32.rs
> +    }
Just inline?

2024-06-04 22:57 UTC, btj commented on tests/rust/safe_abstraction/rc_u32.rs
> +//    if q < q1 { return q/2; } else { return q1/2; }
Insert the following:
```
    lifetime_token_inv(dk);
    ghost_cell_fraction_info(gid);
```

2024-06-26 13:40 UTC, btj commented on bin/rust/rust_belt/lifetime_logic.gh
> +    requires [_]exists(?q) &*& [_]frac_borrow(k, lifetime_token_(q, k1));
You seem to be arguing for the use of `[_]exists` in predicate definitions. That seems different from the use of `[_]exists` in API preconditions? Here, it seems better if the lemma takes `q` as a parameter?

2024-06-26 17:28 UTC, Nima-Rahimi-Foroushaani commented on bin/rust/rust_belt/lifetime_logic.gh
> +    requires [_]exists(?q) &*& [_]frac_borrow(k, lifetime_token_(q, k1));
You are right! Somehow I thought you were talking about `[_]exists` in the `Rc` proof.

2024-07-05 09:44 UTC, btj approved these changes

2024-07-05 09:44 UTC, merged

2024-07-05 09:45 UTC, btj commented
🎉